name: RemovablePortalEyes
version: ${project.version}
description: Removable EndPortal Eyes
author: crashdemons
website: https://github.com/crashdemons
api-version: 1.13
depend: [ WorldGuard ]

main: com.github.crashdemons.removableportaleyes.RPEPlugin